apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sure-repute-ca-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  namespace: ca
spec:
  rules:
    - host: {{ .Values.CA_HOST_NAME }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sure-repute-ca-service
                port:
                  number: 9090