apiVersion: v1
kind: Namespace
metadata:
  name: ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ca-role
  namespace: ca
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: ca
subjects:
  # Google Cloud user account
  - kind: User
    name: rafafigoalexandre@gmail.com
roleRef:
  kind: Role
  name: ca-role
  apiGroup: rbac.authorization.k8s.io
