apiVersion: v1
kind: Secret
metadata:
  labels:
    app: identity-provider-server
  name: identity-provider-secret
  namespace: identity-provider
data:
  DB_USER: {{ .Values.DB_USER }}
  DB_PWD: {{ .Values.DB_PWD }}
type: Opaque