apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-provider-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  namespace: identity-provider
spec:
  rules:
    - host: {{ .Values.CIP_HOST }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-provider-service
                port:
                  number: 9091