apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: identity-provider-server
  name: identity-provider-config
  namespace: identity-provider
data:
  IDENTITY_PROVIDER_URL: https://0.0.0.0:9091
  DB_CONNECTION: identity-provider-psql-service
  DB_PORT: "5432"
  DB_NAME: {{ .Values.DB_NAME }}