apiVersion: v1
kind: Secret
metadata:
  labels:
    app: identity-provider-psql
  name: identity-provider-psql-secret
  namespace: identity-provider
data:
  POSTGRES_USER: {{ .Values.DB_USER }}
  POSTGRES_PASSWORD: {{ .Values.DB_PWD }}
type: Opaque