apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sure-repute-{{ .Values.K8S_ID }}-psql
  name: sure-repute-{{ .Values.K8S_ID }}-psql-secret
  namespace: sure-repute
data:
  POSTGRES_USER: {{ .Values.DB_USER }}
  POSTGRES_PASSWORD: {{ .Values.DB_PWD }}
type: Opaque