apiVersion: v1
kind: Secret
metadata:
  labels:
    app: sure-repute-{{ .Values.K8S_ID }}-server
  name: sure-repute-{{ .Values.K8S_ID }}-secret
  namespace: sure-repute
data:
  DB_USER: {{ .Values.DB_USER }}
  DB_PWD: {{ .Values.DB_PWD }}
type: Opaque