apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: sure-repute-{{ .Values.K8S_ID }}-server
  name: sure-repute-{{ .Values.K8S_ID }}-config
  namespace: sure-repute
data:
  ID: {{ .Values.ID }}
  CLIENT_SERVER_URL: https://0.0.0.0:9092
  SERVER_SERVER_URL: https://0.0.0.0:9093
  IP_SERVER_URL: https://0.0.0.0:9094
  DB_CONNECTION: sure-repute-{{ .Values.K8S_ID }}-psql-service
  DB_PORT: "5432"
  DB_NAME: {{ .Values.DB_NAME }}